### ISSUE TITLE
Add "how to build" documentation

### ISSUE THREAD

**Issue by carlschroedl** [happyjack27/autoredistrict#2]
I'm so coddled by my formal management tools like maven, that I don't even know where to start building this. Could you provide some advice? I need it to verify the size reduction issue.

**Comment by happyjack27** [comment]
I guess it depends on what IDE you use.  mostly whether it auto-compiles
each java file, and how to launch from it.
I use Eclipse, and it auto-compiles, and from there I just right click on
"ui.Applet" and select "Run as... Java Application".
To run it from the command line, you just run "java.exe" and tell it the
classpath and the main class.  the main class is ui.Applet.
If you got a .jar file, your class path is just the jar file.  To export a
jar file in Eclipse, just right click on a file, go to export.. etc.  The
"jar" folder has batch files that show how to launch it from command line.
If you got a different IDE, presumably its something similiar.
If it doesn't auto-compile the class files, well that's of course another
obstacle...

**Comment by happyjack27** [comment]
The build path is utterly simple: everything in /src, plus the one .jar
file, "jcom.dll", which is only used so it can export directly to excel.
(through COM)

[image: Inline image 1]

**Comment by happyjack27** [comment]
alright, did some research and testing, here is the totally bare-bones way to build, if you don't have an auto-compiling IDE:

the completely low-level way to build the class files:

requires at least java 7 JDK. (due to use of generics)
0. make sure you have that in your "path" environment variable,
e.g. in windows, JDK 1.8.0.45:
set PATH=%PATH%;C:\"Program Files"\Java\jdk1.8.0_45\bin\

1. then, from the project root folder, run:

javac.exe -encoding UTF-8 -d bin -cp src;jcom.jar .\src\ui\Applet.java

(on linux or mac, of course, you'd drop the .exe and flip the slashes to / .)

That's it.



A note:  (currently that gives one error - unmappable character for encoding UTF-8.  please just delete that character)


Any case, all you need to compile from the command line is this one line:

javac.exe -encoding UTF-8 -d bin -cp src;jcom.jar .\src\ui\Applet.java

**Comment by carlschroedl** [comment]
After floundering unsuccessfully with Netbeans for a while (I'm not averse to Eclipse, just don't have it installed), I tried the command line steps you suggested. I was able to compile on openJDK 7 by removing the weirdly-encoded degree character and by using:
```
javac -encoding UTF-8 -d bin -cp 'src:jcom.jar' src/ui/Applet.java
```
Note the colon-delimited classpath. A semicolon didn't work. Maybe a Linux/Windows difference?

It's been more than 5 years since I had to think about the classpath, and that was only on a student project, so I appreciate you figuring that out. Even if it seems simple to you, it's rusty territory for me, and probably would have taken a lot longer for me to resolve.

I'm now trying to run the applet via these, or some close variation:
```
java bin/ui/Applet.class
appletviewer bin/ui/Applet.class
```
It's not displaying anything yet. When I run with ```-debug``` flags and type 'run' into jdb, I get:
```
run sun.applet.Main bin/ui/Applet.class
Set uncaught java.lang.Throwable
Set deferred uncaught java.lang.Throwable
> 
VM Started: 
The application exited
```
Any ideas? 

I'll try installing Eclipse tomorrow. Hopefully the project just works in Eclipse.

**Comment by carlschroedl** [comment]
I forgot to mention: I observe this error behavior in both the bigger and the "post-diet" repos.

**Comment by happyjack27** [comment]
i see you haven't executed from command line either.  you have to specify
the classpath there too.  and this program requires you increas the heap
size (it takes a lot of memory) -Xmx4096M
sample batch files for runing (one-liners) are in the /jars folder.  those
are for if you compressed it into a .jar

either way - adding classpath or making a jar - i'd say just google how to
do it.  that's what i'd be doing.

in production one'd jsut use the jar so 'prolly better to go that route.

**Comment by happyjack27** [comment]
K, how to launch from command line, from just the class files.
starting in the "bin" directory (i.e. where all the class files are, type:

 java -Xmx4096M -Xms1024M -classpath .:../jcom.jar ui/Applet

that's it.  the -Xmx and -Xms is just to allocate the memory it needs, the classpath is, well, the class path, and the final parameter is the main class.

**Comment by happyjack27** [comment]
To compress them all into a jar and then run from that jar, go to the bin folder, type:

jar cf autoredistrict.jar *.class

now you have a jar.  to run it out of the jar, type:

java -Xmx4096M -Xms1024M -classpath autoredistrict.jar:../jcom.jar ui/Applet

note you can use -cp for short instead of -classpath

so, i think that covers everything...

**Comment by carlschroedl** [comment]
Thanks for the help. My difficulties ended up coming from `javac` pointing at jdk 8, and `java` at jdk 7. Facepalllm. Can you tell that I haven't done Java development on my personal open source projects VM in a while :) ? After that everything fell into place. The `java` command you specified works. I didn't have time to do much else today. Tomorrow's busy. Will try to get eclipse installed though.

**Comment by carlschroedl** [comment]
Continuing the trend, I use jars/ears/wars a lot and generally know what they are, but I don't know how to make them with barebones jdk tools. The command you suggested to jar and run isn't working for me on linux, but after reading the fine manual, I can create a runnable jar using a couple of commands. From the clone root dir, either:
```
cd bin
find . -name '*.class' -print > classes.list
jar cf autoredistrict.jar @classes.list
```
or by using the globstar shopt
```
cd bin
shopt -s globstar
jar cf autoredistrict.jar **/*.class
```
Both of these are pretty linux-specific. Is there a better cross-platform way?

**Comment by happyjack27** [comment]
that's a bunch of unneccessary steps there.

the jar command is pretty simple.  in reality all it is a zip command.

jar/war/ear are all actually the same exact thing: a .zip file with a
different file extension.  some people thought it was a good idea to add
confusion by giving it multiple names.  "war" stands for "web archive",
generally for servlets, "ear" stands for "enterprise archive", blame IBM
for that one.  they really all are just .jar's, which are really .zip's.

anyways, like the zip or tar command, the command line parameters are just
the destination file, and the source path(s).  though it has a few extra
options (such as the ability to add a manifest file).

so the issue is probably just getting the source path(s) (last parameter)
right.

**Comment by carlschroedl** [comment]
Arrrrgh. Reading is the worst. From man jar:
```
...
inputfiles
             Files or directories, separated by spaces, to be combined into jarfile (for c
             and u), or to be extracted (for x) or listed (for t) from jarfile. All direc-
             tories  are  processed  RECURSIVELY YA IDJIOT. The files are compressed unless option 0
             (zero) is used.
...
```
Some emphasis/self-directed insulting added ;)

So yeah, no need to globstar or find stuff, just gotta specify the dir.

This works from the bin dir:
```
jar cf autoredistrict.jar .
```
I'll add to the pull request or open a new one.
